# Please see the documentation for all configuration options:
# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
  - package-ecosystem: "gitsubmodule"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "thursday"
      time: "08:00"
      timezone: "America/Chicago"
    allow:
      - dependency-name: "demos/pixi-tutorial"
      - dependency-name: "demos/terminal-tutorial"
    commit-message:
      prefix: "automatically updating the demos"
    open-pull-requests-limit: 1
